export const Users = [
  {
    id: 1,
    profilePicture: "https://i.ibb.co/GpW0y16/1.jpg",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "https://i.ibb.co/QrdZWHy/2.jpg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "https://i.ibb.co/6yZQ9zB/3.jpg",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "https://i.ibb.co/hYHbZ3k/4.jpg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "https://i.ibb.co/T1gLmGL/5.jpg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "https://i.ibb.co/KXFnmHn/6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "https://i.ibb.co/85BsZr4/7.jpg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "https://i.ibb.co/drNSxWQ/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "https://i.ibb.co/tJGDkht/9.jpg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "https://i.ibb.co/RBH5M2n/10.jpg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "https://i.ibb.co/gVGMss9/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "https://i.ibb.co/34h2bdh/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "https://i.ibb.co/9Y9HHjX/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "https://i.ibb.co/bRjS23c/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://i.ibb.co/qgJNW3D/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://i.ibb.co/gSGQQDq/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "https://i.ibb.co/nBtqBxk/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://i.ibb.co/JxNLJq7/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "https://i.ibb.co/kBXprcj/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://i.ibb.co/zQRTcW1/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
